### ISSUE TITLE
blank page installing packages

### ISSUE THREAD

**Issue by Nicola1971** [Jako/PackageManager#12]
On some customers servers i'm unable to install packages.
i can upload packages using P.M., but when i trying to install, receive a blank page.
No errors in system reports.
On the same servers the "store" module works without any issue.

**Comment by Jako** [comment]
Any errors in Apache/PHP error log? Which PHP version are you using?

**Comment by Nicola1971** [comment]
is a problem I've always had on some servers not managed by me.
it's not on my servers, so i can't access to log files (i'll ask to the customer) ...and phpInfo() is disabled 

I do not know if it is installed, but should be an issue with modx_security?

**Comment by Nicola1971** [comment]
ok i got a directadmin access, no errors related in the error log

**Comment by Jako** [comment]
Hmm, could you look where/why the module code stops by setting `die('reached)` in the code? Should happen somewhere in packagemanager/packageinstaller class.

**Comment by Nicola1971** [comment]
can't find "die" inside packageinstaller.class

**Comment by Jako** [comment]
You have to insert that line to see where the code stops.

**Comment by Nicola1971** [comment]
ok , where?  :) at the end of the code?

**Comment by Jako** [comment]
Here the code starts: https://github.com/Jako/PackageManager/blob/master/assets/modules/packagemanager/classes/packagemanager.class.php#L151

**Comment by Nicola1971** [comment]
before the funcion ?

**Comment by Jako** [comment]
The blank page is (maybe) caused by some PHP error. So you have to look where where code stops. This could be done by remote debugging (if you have ssh access and some other dependencies – you could google for 'remote debug php tunnel') or by inserting some check points with `die('reached');` in the code.

**Comment by Nicola1971** [comment]
Sorry it's too much for my poor php knowledge :(
 and i've not access to this kind of tools on this server.

**Comment by Jako** [comment]
It is quite easy to check if the current code is executed. Look into the run function and insert/move the `die` code line by line and see where the code is executed (you receive a `reached` output) and when you get only a blank page (If you get a blank page the error occurs before).

If the code executes a function, you have to set/move the `die` code in that function. All lines with $this->functionname() are calling functions in the same class. $this->chunkie->functionname() and $this-> installer->functionname() call functions in Chunkie/PackageInstaller class.

**Comment by Nicola1971** [comment]
tryied (not sure in the correct way) , seems to stop at line 155
echo $this->getInstalledPackages();

**Comment by Jako** [comment]
Could you check this one (and the nested ones) too? https://github.com/Jako/PackageManager/blob/master/assets/modules/packagemanager/classes/packagemanager.class.php#L182
